// Auto-generated by scripts/generate-legal-content.mjs
// Do not edit this file directly.

// source: legal/terms-of-service/ja/2026-02-12.md
export const termsMd = `# 利用規約

最終更新日: 2026年2月12日

本利用規約(以下、「本規約」)は、本サービス(以下、「本サービス」)の利用条件を定めるものです。ユーザーは本規約に同意の上、本サービスを利用します。

## 第1条(定義)

- 「ユーザー」とは、本サービスを利用するすべての者をいいます。
- 「登録ユーザー」とは、アカウント登録を行ったユーザーをいいます。
- 「コンテンツ」とは、ユーザーがアップロードするPDF、テキスト、画像、入力データ等をいいます。

## 第2条(本サービスの内容)

1. 本サービスは、ユーザーがアップロードしたPDFを解析し、AIを用いて内容に関するチャット応答を提供します。
2. 本サービスは、無料プランおよび有料プランを提供します。
3. 運営者は、サービス内容を予告なく変更、停止または終了できます。

## 第3条(アカウント)

1. ユーザーは、正確な情報を登録しなければなりません。
2. ユーザーは、アカウント情報を自己の責任で管理します。
3. 不正利用が疑われる場合、運営者はアカウントを停止できます。

## 第4条(料金および支払)

1. 有料プランは、表示された月額料金に基づき請求されます。
2. 支払はStripe等の外部決済サービスを通じて行われます。
3. 途中解約の場合も、原則として返金は行いません。
4. 料金およびプラン内容は変更される場合があります。
5. 決済情報は決済事業者により管理され、当社はカード情報を保持しません。

## 第5条(禁止事項)

ユーザーは以下の行為を行ってはなりません。

- 法令に違反する行為
- 著作権侵害となるPDFのアップロード
- 個人情報を不正取得または公開する行為
- システムに過度な負荷をかける行為
- リバースエンジニアリング
- 不正アクセス

違反が確認された場合、アカウント停止や削除を行います。

## 第6条(コンテンツの取扱い)

1. ユーザーは、自らがアップロードするコンテンツについて、必要な権利を有していることを保証します。
2. 本サービスはAI処理のため、コンテンツを一時的に保存する場合があります。
3. 運営者は、サービス改善目的で統計情報を利用できます。
4. 権利者から削除依頼があった場合、当社は当該コンテンツを削除し、必要に応じてアカウントを停止します。

## 第7条(AI応答の性質)

1. 本サービスの回答はAIによる生成結果であり、正確性を保証しません。
2. 医療、法律、投資判断等の専門用途への利用は自己責任とします。
3. 出力結果の正確性や妥当性は、ユーザーが確認するものとします。
4. 生成結果の著作権等の取扱いは、ユーザーが適用法令および関係規約を確認の上、適切に扱うものとします。

## 第8条(免責事項)

本サービスの利用により生じた損害について、運営者は責任を負いません。サービス停止、データ消失、外部API障害、決済障害についても同様です。

## 第9条(知的財産権)

本サービスに関する著作権、商標権等は運営者に帰属します。

## 第10条(過度利用の制限)

通常利用の範囲を超える利用や、システムに高い負荷を与える利用が確認された場合、運営者は利用制限や停止を行うことがあります。

## 第11条(未成年の利用)

未成年のユーザーは、親権者等の同意を得た上で本サービスを利用するものとします。

## 第12条(規約変更)

本規約は、予告なく変更される場合があります。

## 第13条(準拠法)

本規約は日本法に準拠します。
`;

// source: legal/terms-of-service/en/2026-02-12.md
export const termsEnMd = `# Terms of Service

Last Updated: February 12, 2026

These Terms of Service ("Terms") set forth the conditions for using this service ("Service"). By using the Service, users agree to these Terms.

## Article 1 (Definitions)

- "User" means any person who uses the Service.
- "Registered User" means a user who has created an account.
- "Content" means PDFs, text, images, and other data uploaded or entered by users.

## Article 2 (Service Overview)

1. The Service analyzes PDFs uploaded by users and provides AI-based chat responses about their contents.
2. The Service offers both free and paid plans.
3. The operator may change, suspend, or discontinue the Service without prior notice.

## Article 3 (Accounts)

1. Users must provide accurate information when registering.
2. Users are responsible for managing their account credentials.
3. The operator may suspend an account if unauthorized use is suspected.

## Article 4 (Fees and Payment)

1. Paid plans are billed based on the monthly price displayed at the time of purchase.
2. Payments are processed through external payment providers such as Stripe.
3. In principle, refunds are not provided for mid-term cancellations.
4. Fees and plan details may be changed.
5. Payment information is managed by the payment provider, and we do not store card details.

## Article 5 (Prohibited Conduct)

Users must not:

- Violate any applicable laws or regulations
- Upload PDFs that infringe copyrights or other rights
- Improperly obtain or disclose personal information
- Place excessive load on the system
- Reverse engineer the Service
- Access the Service without authorization

If a violation is confirmed, the operator may suspend or delete the account.

## Article 6 (Handling of Content)

1. Users represent that they have the necessary rights to upload their content.
2. The Service may temporarily store content for AI processing.
3. The operator may use statistical information for service improvement.
4. If a rights holder requests deletion, we may delete the relevant content and suspend the related account if necessary.

## Article 7 (Nature of AI Responses)

1. Responses provided by the Service are AI-generated and are not guaranteed to be accurate.
2. Use for medical, legal, investment, or other specialized purposes is at the user's own risk.
3. Users are responsible for verifying the accuracy and appropriateness of generated output.
4. Users are responsible for handling generated output in compliance with applicable laws and third-party terms.

## Article 8 (Disclaimer)

The operator is not liable for damages arising from the use of the Service, including service outages, data loss, external API failures, or payment failures.

## Article 9 (Intellectual Property)

Copyrights, trademarks, and other intellectual property rights related to the Service belong to the operator.

## Article 10 (Restrictions on Excessive Use)

If use exceeds normal usage or places a high load on the system, the operator may restrict or suspend access.

## Article 11 (Use by Minors)

Minors may use the Service only with the consent of a parent or legal guardian.

## Article 12 (Changes to the Terms)

These Terms may be changed without prior notice.

## Article 13 (Governing Law)

These Terms are governed by the laws of Japan.
`;

// source: legal/privacy-policy/ja/2026-02-12.md
export const privacyMd = `# プライバシーポリシー

最終更新日: 2026年2月12日

本ポリシーは、本サービスにおける個人情報の取扱いを定めるものです。

## 1. 取得する情報

- アカウント情報(メールアドレス、IDなど)
- 支払情報(Stripeを通じて取得される取引情報)
- アップロードされたPDFの内容
- ログ情報(IPアドレス、利用履歴)
- Cookie等の識別子

## 2. 利用目的

- サービス提供および運営
- 課金管理
- 不正利用防止
- サービス改善
- 法令対応

## 3. 第三者提供

1. 決済処理のためStripeへ必要情報を提供します。
2. AI処理のため外部API提供事業者へ送信する場合があります。
3. 法令に基づく場合を除き、本人同意なく第三者へ提供しません。

## 4. 外部送信・海外サーバー

本サービスでは、AI処理等のために国外のサーバーを利用する場合があります。外部送信の有無や送信先は、提供事業者の規約に従い管理されます。

## 5. データ保存期間

コンテンツは原則として一定期間後に削除します。法令上必要な場合を除きます。

## 6. セキュリティ

適切な安全管理措置を講じ、情報漏洩防止に努めます。

## 7. ユーザーの権利

ユーザーは、自己の個人情報について、開示・訂正・削除を請求できます。

## 8. Cookie

本サービスは利便性向上のためCookieを利用します。

## 9. 学習利用

API経由で送信されたデータの再学習利用の有無は、外部サービスの規約に従います。

## 10. お問い合わせ

プライバシーに関する問い合わせは、指定の連絡先まで行ってください。
`;

// source: legal/privacy-policy/en/2026-02-12.md
export const privacyEnMd = `# Privacy Policy

Last Updated: February 12, 2026

This Privacy Policy explains how we handle personal information in connection with the Service.

## 1. Information We Collect

- Account information such as email address and user ID
- Payment-related information obtained through Stripe
- Contents of uploaded PDFs
- Log information such as IP address and usage history
- Cookies and similar identifiers

## 2. Purposes of Use

- Providing and operating the Service
- Managing billing and payments
- Preventing unauthorized or abusive use
- Improving the Service
- Complying with legal obligations

## 3. Sharing with Third Parties

1. We may provide necessary information to Stripe for payment processing.
2. We may transmit data to external API providers for AI processing.
3. Except as required by law, we do not provide personal information to third parties without the user's consent.

## 4. External Transfers and Overseas Servers

The Service may use servers located outside Japan for AI processing and related operations. Any external transfers are managed in accordance with the policies of the relevant providers.

## 5. Data Retention

Content is generally deleted after a certain period unless retention is required by law.

## 6. Security

We implement appropriate security measures and strive to prevent unauthorized access and data leakage.

## 7. User Rights

Users may request access to, correction of, or deletion of their personal information.

## 8. Cookies

The Service uses cookies to improve usability and service operation.

## 9. Model Training

Whether data sent through APIs is used for model training depends on the terms of the relevant external service providers.

## 10. Contact

For privacy-related inquiries, please contact us using the designated support channel.
`;

// source: legal/tokushoho/ja/2026-03-07.md
export const tokushoMd = `# 特定商取引法に基づく表記

最終更新日: 2026年3月7日

| 項目 | 内容 |
| --- | --- |
| 法人名（事業者名） | 請求があった場合、遅滞なく開示いたします。 |
| 住所 | 渋谷オフィス<br>〒150-0043<br>東京都渋谷区道玄坂1丁目10番8号渋谷道玄坂東急ビル2F−C |
| 電話番号 | 請求があった場合、遅滞なく開示いたします。 |
| メールアドレス | support@ask-pdf.net |
| 運営責任者 | 麦田晃基 |
| 追加手数料 | インターネット接続に必要な通信料等はユーザーの負担となります。 |
| 交換および返品に関するポリシー | ＜お客様都合による返金・交換＞ デジタルサービスの性質上、原則として購入後の返金・交換は受け付けておりません。<br><br>＜不具合等による返金対応＞ サービス提供に重大な不具合があり当社が妥当と判断した場合は、個別に返金または代替対応を行います。support@ask-pdf.net までご連絡ください。 |
| 配達時間 | デジタルサービスのため、決済完了後に即時提供されます。 |
| 利用可能な決済手段 | クレジットカード決済（Stripe） |
| 決済期間 | クレジットカード決済は申込時に即時処理され、サブスクリプションは毎月の更新時に自動課金されます。 |
| 価格 | 各プランの料金ページに税込価格を記載しております。 |
`;

